# Numpy Tutorials

In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
myarr.size

9

In [4]:
myarr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
myarr.resize((3,3))

In [10]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
myarr.resize((1,9))

In [8]:
myarr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
a = np.arange(9)

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a.resize(3,3)

In [16]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
b = np.identity(3)

In [19]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
c = a+b

In [23]:
d = a-b

In [24]:
c==d

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [25]:
c

array([[1., 1., 2.],
       [3., 5., 5.],
       [6., 7., 9.]])

In [26]:
d

array([[-1.,  1.,  2.],
       [ 3.,  3.,  5.],
       [ 6.,  7.,  7.]])

In [27]:
c is d

False

In [28]:
c in d

True

In [29]:
d in c

True

In [30]:
a.dot(b)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [31]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
d = np.eye(3,4)

In [39]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
d.resize(1,12)

In [41]:
d

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [42]:
d.flat

In [44]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [47]:
nm = [i for i in d.flat if i>0]
# d.flat will give one by one element from array

In [48]:
nm

[1.0, 1.0, 1.0]

In [49]:
myarr.shape

(3, 3)

In [50]:
linear_Space_Arr = np.linspace(1,2,33)

In [51]:
linear_Space_Arr

array([1.     , 1.03125, 1.0625 , 1.09375, 1.125  , 1.15625, 1.1875 ,
       1.21875, 1.25   , 1.28125, 1.3125 , 1.34375, 1.375  , 1.40625,
       1.4375 , 1.46875, 1.5    , 1.53125, 1.5625 , 1.59375, 1.625  ,
       1.65625, 1.6875 , 1.71875, 1.75   , 1.78125, 1.8125 , 1.84375,
       1.875  , 1.90625, 1.9375 , 1.96875, 2.     ])

In [52]:
linear_Space_Arr.resize(3,11)

In [53]:
linear_Space_Arr

array([[1.     , 1.03125, 1.0625 , 1.09375, 1.125  , 1.15625, 1.1875 ,
        1.21875, 1.25   , 1.28125, 1.3125 ],
       [1.34375, 1.375  , 1.40625, 1.4375 , 1.46875, 1.5    , 1.53125,
        1.5625 , 1.59375, 1.625  , 1.65625],
       [1.6875 , 1.71875, 1.75   , 1.78125, 1.8125 , 1.84375, 1.875  ,
        1.90625, 1.9375 , 1.96875, 2.     ]])

In [56]:
linear_Space_Arr.ravel()
# return 1D array or flat Array

array([1.     , 1.03125, 1.0625 , 1.09375, 1.125  , 1.15625, 1.1875 ,
       1.21875, 1.25   , 1.28125, 1.3125 , 1.34375, 1.375  , 1.40625,
       1.4375 , 1.46875, 1.5    , 1.53125, 1.5625 , 1.59375, 1.625  ,
       1.65625, 1.6875 , 1.71875, 1.75   , 1.78125, 1.8125 , 1.84375,
       1.875  , 1.90625, 1.9375 , 1.96875, 2.     ])

# Axis in numpy

AXIS1 ------>
AXIS0    |____________|
|        |____________|
|        |____________|
V        |____________|

In [57]:
My_AXIS_LEARN_ARR = np.arange(9)

In [59]:
My_AXIS_LEARN_ARR.resize((3,3))

In [60]:
My_AXIS_LEARN_ARR

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
My_AXIS_LEARN_ARR.sum(axis=0)
# 0+3+6
# 1+4+7
# 2+5+8

array([ 9, 12, 15])

In [63]:
My_AXIS_LEARN_ARR.sum(axis=1)
# 0+1+2
# 3+4+5
# 6+7+8

array([ 3, 12, 21])

In [64]:
My_AXIS_LEARN_ARR.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [65]:
for element in My_AXIS_LEARN_ARR.flat:
    print(element)

0
1
2
3
4
5
6
7
8


In [66]:
My_AXIS_LEARN_ARR

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
My_AXIS_LEARN_ARR.ndim
#dimention of array

2

In [68]:
My_AXIS_LEARN_ARR.size
#total length of array

9

In [69]:
My_AXIS_LEARN_ARR.nbytes
# total memory used by array

36

In [70]:
My_AXIS_LEARN_ARR.argmax()
#return the index of maximum element

8

In [71]:
My_AXIS_LEARN_ARR.argmin()
#return the index of minimum element

0

In [73]:
reversed_=My_AXIS_LEARN_ARR.T

In [75]:
reversed_[0][0] = 9

In [76]:
reversed_

array([[9, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [77]:
reversed_.argmax()
#index of maximum element

0

In [78]:
reversed_.argsort()
#indexes of element to sort

array([[1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [79]:
reversed_

array([[9, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [80]:
reversed_.argmax(axis=0)

array([0, 2, 2], dtype=int64)

In [81]:
reversed_.reshape((9,1))

array([[9],
       [3],
       [6],
       [1],
       [4],
       [7],
       [2],
       [5],
       [8]])

In [82]:
reversed_

array([[9, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [83]:
reversed_.resize((9,1))

In [84]:
reversed_

array([[9],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [91]:
np.sqrt(reversed_)

array([[3.        ],
       [1.        ],
       [1.41421356],
       [1.73205081],
       [2.        ],
       [2.23606798],
       [2.44948974],
       [2.64575131],
       [2.82842712]])

In [93]:
reversed_.max()
#return max element

9

In [94]:
np.where(reversed_>4)
#index of elm which satisfy the condition

(array([0, 5, 6, 7, 8], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64))

In [95]:
reversed_

array([[9],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [96]:
np.count_nonzero(reversed_)

9

In [97]:
np.nonzero(reversed_)
#return index of elm which are non zeros

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [98]:
np.empty( (2,3) )
#uninialized array

array([[inf, inf, inf],
       [inf, inf, inf]])

In [101]:
# random elem array
rg = np.random.default_rng(1)
a = rg.random((2,3))

In [102]:
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

# slicing in numpy

In [103]:
a[1:3]

array([[0.94864945, 0.31183145, 0.42332645]])

In [104]:
a[0:2]

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [105]:
# negative indices
a[-1]

array([0.94864945, 0.31183145, 0.42332645])

In [106]:
np.ceil(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [107]:
np.floor(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

# Trigonometry Functions 

In [111]:
data = np.sin(np.arange(25)).reshape(5,5)

In [112]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

# Matrix Functionality

In [113]:
np.linalg.inv(data)

array([[-5.82081690e+15, -4.62749979e+15,  1.85678080e+15,
        -9.73322105e+15,  3.17883396e+15],
       [-6.68535453e+15,  8.17600074e+15, -4.10852730e+15,
         1.51056430e+15,  5.06354394e+15],
       [ 8.60380601e+15, -6.58448338e+15,  6.56774946e+15,
         0.00000000e+00, -3.00239975e+15],
       [-1.34112647e+16,  1.58217353e+15, -4.73816211e+15,
        -9.00719925e+15,  5.25419957e+15],
       [ 4.03393249e+14,  1.47447973e+15,  2.43944980e+15,
         0.00000000e+00,  3.00239975e+15]])

In [114]:
 np.trace(data)

-2.4725540249776605

In [115]:
data.T

array([[ 0.        , -0.95892427, -0.54402111,  0.65028784,  0.91294525],
       [ 0.84147098, -0.2794155 , -0.99999021, -0.28790332,  0.83665564],
       [ 0.90929743,  0.6569866 , -0.53657292, -0.96139749, -0.00885131],
       [ 0.14112001,  0.98935825,  0.42016704, -0.75098725, -0.8462204 ],
       [-0.7568025 ,  0.41211849,  0.99060736,  0.14987721, -0.90557836]])

In [125]:
y = np.arange(0,5).reshape((5,1))
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [126]:
np.linalg.solve(data, y)

array([[-1.73982655e+16],
       [ 2.47448148e+16],
       [-5.45858347e+15],
       [-1.38989502e+16],
       [ 1.83629783e+16]])